### ISSUE TITLE
Ubuntu Compile

### ISSUE THREAD

**Issue by Chronos6** [marcogulino/AndroidUsbCamera#2]
I'm trying to compile it under ubuntu, but something must be not clear.. I try to compile and i get many errors. There a lot more, i just copy a few lines. Can somebody help me how to compile it? Thanks.

...
/usr/local/lib/libavformat.a(rtmppkt.o): In function `ff_rtmp_packet_destroy':
/home/chronos/ffmpeg/libavformat/rtmppkt.c:190: undefined reference to`av_freep'
/usr/local/lib/libavformat.a(rtmppkt.o): In function `ff_rtmp_packet_create':
/home/chronos/ffmpeg/libavformat/rtmppkt.c:174: undefined reference to`av_malloc'
/usr/local/lib/libavformat.a(rtmppkt.o): In function `ff_amf_write_number':
/home/chronos/ffmpeg/libavformat/rtmppkt.c:38: undefined reference to`av_dbl2int'
/usr/local/lib/libavformat.a(rtmppkt.o): In function `ff_rtmp_packet_create':
/home/chronos/ffmpeg/libavformat/rtmppkt.c:174: undefined reference to`av_malloc'
/usr/local/lib/libavformat.a(rtmppkt.o): In function `ff_amf_get_field_value':
/home/chronos/ffmpeg/libavformat/rtmppkt.c:255: undefined reference to`av_int2dbl'
/home/chronos/ffmpeg/libavformat/rtmppkt.c:262: undefined reference to `av_strlcpy'
/usr/local/lib/libavformat.a(rtpproto.o): In function`rtp_close':
/home/chronos/ffmpeg/libavformat/rtpproto.c:283: undefined reference to `av_free'
/usr/local/lib/libavformat.a(rtpproto.o): In function`url_add_option':
/home/chronos/ffmpeg/libavformat/rtpproto.c:90: undefined reference to `av_strlcat'
/home/chronos/ffmpeg/libavformat/rtpproto.c:94: undefined reference to`av_strlcat'
/home/chronos/ffmpeg/libavformat/rtpproto.c:92: undefined reference to `av_strlcat'
/usr/local/lib/libavformat.a(rtpproto.o): In function`rtp_open':
/home/chronos/ffmpeg/libavformat/rtpproto.c:131: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libavformat/rtpproto.c:184: undefined reference to`av_free'
/usr/local/lib/libavformat.a(tcp.o): In function `tcp_close':
/home/chronos/ffmpeg/libavformat/tcp.c:180: undefined reference to`av_free'
/usr/local/lib/libavformat.a(tcp.o): In function `tcp_open':
/home/chronos/ffmpeg/libavformat/tcp.c:96: undefined reference to`av_malloc'
/usr/local/lib/libavformat.a(udp.o): In function `udp_close':
/home/chronos/ffmpeg/libavformat/udp.c:523: undefined reference to`av_free'
/usr/local/lib/libavformat.a(udp.o): In function `udp_leave_multicast_group':
/home/chronos/ffmpeg/libavformat/udp.c:134: undefined reference to`av_log'
/home/chronos/ffmpeg/libavformat/udp.c:122: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_ipv6_resolve_host':
/home/chronos/ffmpeg/libavformat/udp.c:161: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_open':
/home/chronos/ffmpeg/libavformat/udp.c:363: undefined reference to `av_mallocz'
/usr/local/lib/libavformat.a(udp.o): In function`udp_socket_create':
/home/chronos/ffmpeg/libavformat/udp.c:206: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_open':
/home/chronos/ffmpeg/libavformat/udp.c:459: undefined reference to `av_free'
/usr/local/lib/libavformat.a(udp.o): In function`udp_join_multicast_group':
/home/chronos/ffmpeg/libavformat/udp.c:106: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_open':
/home/chronos/ffmpeg/libavformat/udp.c:448: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_set_multicast_ttl':
/home/chronos/ffmpeg/libavformat/udp.c:78: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_port':
/home/chronos/ffmpeg/libavformat/udp.c:232: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o): In function`udp_open':
/home/chronos/ffmpeg/libavformat/udp.c:440: undefined reference to `av_log'
/usr/local/lib/libavformat.a(udp.o):/home/chronos/ffmpeg/libavformat/udp.c:94: more undefined references to`av_log' follow
/usr/local/lib/libavformat.a(cutils.o): In function `ff_dynarray_add':
/home/chronos/ffmpeg/libavformat/cutils.c:36: undefined reference to`av_realloc'
/usr/local/lib/libavformat.a(metadata.o): In function `av_metadata_free':
/home/chronos/ffmpeg/libavformat/metadata.c:87: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:88: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:90: undefined reference to`av_free'
/usr/local/lib/libavformat.a(metadata.o): In function `av_metadata_set':
/home/chronos/ffmpeg/libavformat/metadata.c:55: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libavformat/metadata.c:62: undefined reference to `av_realloc'
/home/chronos/ffmpeg/libavformat/metadata.c:58: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:59: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:69: undefined reference to`av_strdup'
/home/chronos/ffmpeg/libavformat/metadata.c:70: undefined reference to `av_strdup'
/home/chronos/ffmpeg/libavformat/metadata.c:74: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:75: undefined reference to `av_freep'
/usr/local/lib/libavformat.a(metadata.o): In function`av_metadata_free':
/home/chronos/ffmpeg/libavformat/metadata.c:92: undefined reference to `av_freep'
/home/chronos/ffmpeg/libavformat/metadata.c:87: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:88: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:90: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata.c:92: undefined reference to `av_freep'
/usr/local/lib/libavformat.a(metadata_compat.o): In function`ff_metadata_demux_compat':
/home/chronos/ffmpeg/libavformat/metadata_compat.c:68: undefined reference to `av_strlcpy'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:77: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:78: undefined reference to `av_strdup'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:85: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:86: undefined reference to `av_strdup'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:89: undefined reference to`av_free'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:90: undefined reference to `av_strdup'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:98: undefined reference to`av_strlcpy'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:100: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/metadata_compat.c:101: undefined reference to`av_strdup'
/usr/local/lib/libavformat.a(options.o): In function `avformat_alloc_context':
/home/chronos/ffmpeg/libavformat/options.c:80: undefined reference to`av_malloc'
/usr/local/lib/libavformat.a(options.o): In function `avformat_get_context_defaults':
/home/chronos/ffmpeg/libavformat/options.c:74: undefined reference to`av_opt_set_defaults'
/usr/local/lib/libavformat.a(options.o): In function `avformat_alloc_context':
/home/chronos/ffmpeg/libavformat/options.c:80: undefined reference to`av_malloc'
/usr/local/lib/libavformat.a(options.o): In function `avformat_get_context_defaults':
/home/chronos/ffmpeg/libavformat/options.c:74: undefined reference to`av_opt_set_defaults'
/usr/local/lib/libavformat.a(riff.o): In function `ff_parse_specific_params':
/home/chronos/ffmpeg/libavformat/riff.c:521: undefined reference to`av_gcd'
/usr/local/lib/libavformat.a(riff.o): In function `ff_put_wav_header':
/home/chronos/ffmpeg/libavformat/riff.c:332: undefined reference to`av_get_bits_per_sample'
/home/chronos/ffmpeg/libavformat/riff.c:336: undefined reference to `av_log'
/usr/local/lib/libavformat.a(riff.o): In function`ff_get_wav_header':
/home/chronos/ffmpeg/libavformat/riff.c:471: undefined reference to `av_mallocz'
/usr/local/lib/libavformat.a(rtp_asf.o): In function`asfrtp_free_context':
/home/chronos/ffmpeg/libavformat/rtp_asf.c:263: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:265: undefined reference to`av_freep'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:266: undefined reference to `av_free'
/usr/local/lib/libavformat.a(rtp_asf.o): In function`asfrtp_parse_packet':
/home/chronos/ffmpeg/libavformat/rtp_asf.c:246: undefined reference to `av_free_packet'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:196: undefined reference to `av_free'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:222: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:218: undefined reference to `av_log_missing_feature'
/usr/local/lib/libavformat.a(rtp_asf.o): In function`asfrtp_new_context':
/home/chronos/ffmpeg/libavformat/rtp_asf.c:254: undefined reference to `av_mallocz'
/usr/local/lib/libavformat.a(rtp_asf.o): In function`asfrtp_parse_sdp_line':
/home/chronos/ffmpeg/libavformat/rtp_asf.c:121: undefined reference to `av_strstart'
/usr/local/lib/libavformat.a(rtp_asf.o): In function`ff_wms_parse_sdp_a_line':
/home/chronos/ffmpeg/libavformat/rtp_asf.c:96: undefined reference to `av_strstart'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:100: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:101: undefined reference to `av_base64_decode'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:104: undefined reference to`av_log'
/home/chronos/ffmpeg/libavformat/rtp_asf.c:113: undefined reference to `av_free'
/usr/local/lib/libavformat.a(rtp_mpv.o): In function`ff_rtp_send_mpegvideo':
/home/chronos/ffmpeg/libavformat/rtp_mpv.c:59: undefined reference to `ff_find_start_code'
/home/chronos/ffmpeg/libavformat/rtp_mpv.c:59: undefined reference to`ff_find_start_code'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeContext':
/home/chronos/ffmpeg/libswscale/swscale.c:3424: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3425: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3430: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3431: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3436: undefined reference to`av_freep'
/usr/local/lib/libswscale.a(swscale.o):/home/chronos/ffmpeg/libswscale/swscale.c:3437: more undefined references to `av_freep' follow
/usr/local/lib/libswscale.a(swscale.o): In function`sws_printVec2':
/home/chronos/ffmpeg/libswscale/swscale.c:3384: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:3385: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:3386: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function `pal2rgbWrapper':
/home/chronos/ffmpeg/libswscale/swscale.c:2032: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2042: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function `rgb2rgbWrapper':
/home/chronos/ffmpeg/libswscale/swscale.c:2106: undefined reference to`av_log'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function `rgb2rgbWrapper':
/home/chronos/ffmpeg/libswscale/swscale.c:2110: undefined reference to`av_log'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/usr/local/lib/libswscale.a(swscale.o): In function `initFilter':
/home/chronos/ffmpeg/libswscale/swscale.c:1362: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1431: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1392: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1519: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:1537: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:1600: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1677: undefined reference to`av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:1678: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:1367: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:1519: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:1600: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1606: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:1378: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:1431: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:1649: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:1649: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_printVec2':
/home/chronos/ffmpeg/libswscale/swscale.c:3384: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:3385: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:3386: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getContext':
/home/chronos/ffmpeg/libswscale/swscale.c:2472: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getContext':
/home/chronos/ffmpeg/libswscale/swscale.c:2476: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2498: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2503: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2510: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2825: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:2826: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:2688: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2828: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2832: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2832: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2751: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2752: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2753: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2754: undefined reference to`av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2836: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:2836: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2825: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2492: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2841: undefined reference to `av_mallocz'
/home/chronos/ffmpeg/libswscale/swscale.c:2841: undefined reference to`av_log'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getContext':
/home/chronos/ffmpeg/libswscale/swscale.c:2678: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2879: undefined reference to`av_log'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getContext':
/home/chronos/ffmpeg/libswscale/swscale.c:2884: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2891: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2912: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2919: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2943: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o):/home/chronos/ffmpeg/libswscale/swscale.c:2954: more undefined references to`av_log' follow
/usr/local/lib/libswscale.a(swscale.o): In function `sws_format_name':
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to`av_pix_fmt_descriptors'
/home/chronos/ffmpeg/libswscale/swscale.c:381: undefined reference to `av_pix_fmt_descriptors'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getContext':
/home/chronos/ffmpeg/libswscale/swscale.c:2887: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2754: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2952: undefined reference to `av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2950: undefined reference to`av_log'
/home/chronos/ffmpeg/libswscale/swscale.c:2947: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o):/home/chronos/ffmpeg/libswscale/swscale.c:2863: more undefined references to`av_log' follow
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/usr/local/lib/libswscale.a(swscale.o): In function`swScale_MMX2':
/home/chronos/ffmpeg/libswscale/swscale_template.c:2606: undefined reference to `av_log'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_convVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3348: undefined reference to`av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3351: undefined reference to `av_free'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getConvVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_getConstVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_addVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3330: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3333: undefined reference to`av_free'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_subVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3339: undefined reference to`av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3342: undefined reference to `av_free'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_shiftVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3321: undefined reference to `av_free'
/home/chronos/ffmpeg/libswscale/swscale.c:3324: undefined reference to`av_free'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_getDefaultFilter':
/home/chronos/ffmpeg/libswscale/swscale.c:3122: undefined reference to`av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to`av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to `av_malloc'
/usr/local/lib/libswscale.a(swscale.o):/home/chronos/ffmpeg/libswscale/swscale.c:3179: more undefined references to`av_malloc' follow
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_allocVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3179: undefined reference to `av_malloc'
/home/chronos/ffmpeg/libswscale/swscale.c:3183: undefined reference to`av_malloc'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3400: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to `av_free'
/usr/local/lib/libswscale.a(swscale.o): In function`sws_getIdentityVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to`av_freep'
/home/chronos/ffmpeg/libswscale/swscale.c:3185: undefined reference to `av_freep'
/usr/local/lib/libswscale.a(swscale.o):/home/chronos/ffmpeg/libswscale/swscale.c:3185: more undefined references to`av_freep' follow
/usr/local/lib/libswscale.a(swscale.o): In function `sws_scale':
/home/chronos/ffmpeg/libswscale/swscale.c:3001: undefined reference to`av_log'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeContext':
/home/chronos/ffmpeg/libswscale/swscale.c:3475: undefined reference to`av_free'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeVec':
/home/chronos/ffmpeg/libswscale/swscale.c:3402: undefined reference to`av_free'
/usr/local/lib/libswscale.a(swscale.o): In function `sws_freeFilter':
/home/chronos/ffmpeg/libswscale/swscale.c:3413: undefined reference to`av_free'
collect2: ld returned 1 exit status
make[2]: **\* [AndroidUsbCamera] Error 1
make[1]: **\* [CMakeFiles/AndroidUsbCamera.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Chronos6** [comment]
I'm using Lucid now, and it works. Dont know if anybody cares..

**Comment by projektdotnet** [comment]
had this issue on 10.04 but solved it with a few extra libraries
libswscale-dev libavformat-dev libavcodec-dev
install those three (and their auto-generated dependencies) and you should have no more errors on compile
