### ISSUE TITLE
Can't make it compile

### ISSUE THREAD

**Issue by comtom** [marcogulino/AndroidUsbCamera#9]
I'm trying to compile it but i can't. I have Debian Sid, with all the dependencies needed and i get this error while running make:

comtom@nemetona ~/src/AndroidUsbCamera/build $ make
[  5%] Generating socketinterface.moc
Scanning dependencies of target qtInterfaces_lib
[ 11%] Building CXX object src/qtInterfaces/CMakeFiles/qtInterfaces_lib.dir/socketinterface.cpp.o
Linking CXX static library libqtInterfaces_lib.a
[ 11%] Built target qtInterfaces_lib
[ 17%] Generating socketconnector.moc
[ 23%] Generating framesconverter.moc
[ 29%] Generating androidusbcamera.moc
[ 35%] Generating framesfactory.moc
[ 41%] Generating frame.moc
[ 47%] Generating framescreator.moc
[ 52%] Generating framesdataextractor.moc
Scanning dependencies of target AndroidUsbCameraStaticLib
[ 58%] Building CXX object src/CMakeFiles/AndroidUsbCameraStaticLib.dir/framesconverter.cpp.o
In file included from /usr/include/libavutil/avutil.h:81,
from /usr/include/libavcodec/avcodec.h:30,
from /home/comtom/src/AndroidUsbCamera/src/framesconverter.cpp:28:
/usr/include/libavutil/common.h: In function ‘int32_t av_clipl_int32(int64_t)’:
/usr/include/libavutil/common.h:154: error: ‘UINT64_C’ was not declared in this scope
make[2]: **\* [src/CMakeFiles/AndroidUsbCameraStaticLib.dir/framesconverter.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/AndroidUsbCameraStaticLib.dir/all] Error 2
make: **\* [all] Error 2

Any workaround here?
Thanks!

**Comment by unchiujar** [comment]
I have exactly the same problem

**Comment by comtom** [comment]
Still can't do it. Any help please?

**Comment by unchiujar** [comment]
Found an workaround.
Do everything until it fails and then edit CMakeCache.txt and add to the line 40  

-D__STDC_CONSTANT_MACROS

The problem is with some library that doesn't respect standards (so says google) and this compiler flag seems to work around the problem.

**Comment by comtom** [comment]
Seems to work. At least i have the binary done. I will post the result of few tests.
Thanks for your help!

**Comment by lukus** [comment]
Worked here too .. thanks.

**Comment by juzna** [comment]
It still fails to build for me, this workaround just moves me further. But then I'm geting:
    Linking CXX executable AndroidUsbCamera
    /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/libavformat.so: undefined reference to `ff_log_missing_feature@LIBAVCODEC_52'

Any ideas?

**Comment by unchiujar** [comment]
Are  the ffmpeg libraries installed ?

**Comment by manishahg** [comment]
# sudo gedit /usr/include/libavutil/common.h

```
   add these lines : 
    #  if !defined (UINT64_MAX)
    #   define UINT64_MAX  18446744073709551615ULL
    #  endif
    #  if !defined (INT64_MAX)
    #   define INT64_MAX  9223372036854775807LL
    #  endif
    #ifndef INT64_C
    #define INT64_C(x)   (x + (INT64_MAX - INT64_MAX))
    #define UINT64_C(x)  (x + (UINT64_MAX - UINT64_MAX))
    #endif
   save and exit
```
